# Generated by Django 4.2.13 on 2024-06-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('reporting_manager', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('date_of_joining', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RecentProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_release_account', models.CharField(max_length=100)),
                ('last_release_ig', models.CharField(max_length=100)),
                ('last_release_date', models.DateField()),
                ('updated_resume', models.FileField(upload_to='resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_skill', models.CharField(max_length=50)),
                ('detailed_skill', models.CharField(max_length=300)),
                ('trained_skill', models.CharField(max_length=100)),
                ('demand_role', models.CharField(max_length=50)),
                ('career_role', models.CharField(max_length=50)),
                ('service_line', models.CharField(max_length=50)),
                ('sub_service_line', models.CharField(max_length=50)),
                ('experience', models.FloatField()),
            ],
        ),
    ]
