# Generated by Django 4.2.13 on 2024-06-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('resources', models.ManyToManyField(to='resource_management_app.personaldetails')),
            ],
        ),
    ]
