# Generated by Django 4.2.13 on 2024-06-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management_app', '0002_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
