# Generated by Django 4.2.13 on 2024-06-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management_app', '0003_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
                ('bench_classification', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=15)),
                ('sub_category', models.CharField(max_length=15)),
                ('talent_category', models.CharField(max_length=15)),
                ('talent_type', models.CharField(max_length=15)),
                ('relocation', models.CharField(max_length=5)),
                ('tm_spoc', models.CharField(max_length=50)),
                ('sl_poc', models.CharField(max_length=50)),
                ('profile_available', models.CharField(max_length=5)),
                ('action_owner', models.CharField(max_length=10)),
                ('aging_bucket', models.CharField(max_length=50)),
                ('wfo', models.CharField(max_length=5)),
                ('assessment_score', models.IntegerField()),
                ('proficiency_status', models.CharField(max_length=15)),
                ('experience_level', models.CharField(max_length=10)),
            ],
        ),
    ]
