# Generated by Django 4.2.13 on 2024-06-20 09:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management_app', '0004_advanceddetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanceddetails',
            name='aging_bucket',
        ),
        migrations.RemoveField(
            model_name='advanceddetails',
            name='country',
        ),
        migrations.RemoveField(
            model_name='advanceddetails',
            name='region',
        ),
        migrations.AddField(
            model_name='advanceddetails',
            name='aging',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advanceddetails',
            name='aging_cluster',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='advanceddetails',
            name='bench_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='advanceddetails',
            name='doj',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='advanceddetails',
            name='experience_level_fresher',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='advanceddetails',
            name='last_release_account',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='advanceddetails',
            name='last_release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='advanceddetails',
            name='last_release_industry_group',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='advanceddetails',
            name='action_owner',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='advanceddetails',
            name='assessment_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advanceddetails',
            name='bench_classification',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='advanceddetails',
            name='category',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='advanceddetails',
            name='experience_level',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='advanceddetails',
            name='proficiency_status',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='advanceddetails',
            name='profile_available',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='advanceddetails',
            name='relocation',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='advanceddetails',
            name='sl_poc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sl_poc', to='resource_management_app.personaldetails'),
        ),
        migrations.AlterField(
            model_name='advanceddetails',
            name='sub_category',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='advanceddetails',
            name='talent_category',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='advanceddetails',
            name='talent_type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='advanceddetails',
            name='tm_spoc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tm_spoc', to='resource_management_app.personaldetails'),
        ),
        migrations.AlterField(
            model_name='advanceddetails',
            name='wfo',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
