# Generated by Django 4.2.13 on 2024-06-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management_app', '0007_client_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.AddField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
