# Generated by Django 3.0.4 on 2020-04-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djstudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('marks', models.IntegerField()),
                ('phonenumber', models.BigIntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
    ]
